### ISSUE TITLE
Selecting year

### ISSUE THREAD

**Issue by NookieGrey** [afialapis/reactstrap-date-picker#22]
Is it any plans for creating year selection?

Problem:
If we use datepicker for dates like 1960 we need to click many times to set this date

**Comment by afialapis** [comment]
Added [`pickMonthElement` property](https://github.com/afialapis/reactstrap-date-picker#pickmonthelement). `1.0.3` version is up with it.

Probably `default` is not enough for "everybody" from a styling perspective: (basically, the `<select>` rendered by `reactstrap-date-picker` having slight UI differences with others `<select>` or `DropDown` in the same page). That's why we also have the chance to put some custom `Element` there.
